# Generated by Django 2.1.5 on 2019-03-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodimage',
            options={'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
        migrations.AlterModelOptions(
            name='goodsku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.AlterModelOptions(
            name='goodspu',
            options={'verbose_name': '商品SPU', 'verbose_name_plural': '商品SPU'},
        ),
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'verbose_name': '首页促销活动', 'verbose_name_plural': '首页促销活动'},
        ),
        migrations.AlterModelOptions(
            name='indexcarousel',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
        migrations.AlterModelOptions(
            name='indexgoods',
            options={'verbose_name': '首页商品列表', 'verbose_name_plural': '首页商品列表'},
        ),
    ]
